PRODUCT_PACKAGES += \
	PUIThemeAndroidQuickPanelIcon \
	PUIThemeAndroidStatIcon \
	PUIThemeBatteryIcon \
	PUIThemeBrightIcon \
	PUIThemeDarkThemeIcon \
	PUIThemedDigitalHealthSettingIcon \
	PUIThemedLineagesBrightIcon \
	PUIThemedLineagesIcons \
	PUIThemedLineagesQuickPanelIcon \
	PUIThemedLineagesRingIcon \
	PUIThemedLineagesSetIcon \
	PUIThemedLineagesSettingsIcon \
	PUIThemedLineagesUSBAndroidIcons \
	PUIThemedRuleIcon \
	PUIThemedSettingsIcon \
	PUIThemedTranslateIcon \
	PUIThemeEasterEggs \
	PUIThemeLayout \
	PUIThemeNoInternetWifiSignal \
	PUIThemePowerPanelIconFramework \
	PUIThemePowerPanelIconSystemUI \
	PUIThemeQSShapeGradient \
	PUIThemeRadius \
	PUIThemeSettingsDebugBool \
	PUIThemeSignalIcon \
	PUIThemeSignalLogoIcon \
	PUIThemeSonyHDIcon \
	PUIThemeSystemUILockScreenIcon \
	PUIThemeSystemUIQuickPanelIcon \
	PUIThemeSystemUIStatIcon
